# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prototype01' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prototype01
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'  

  target 'prototype01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'prototype01UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
