# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'prototype02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for prototype02
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'JSQMessagesViewController'

  target 'prototype02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'prototype02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
